<div data-block="visits-history">
    <div data-bind="scope: 'visits_history'" style="width: 100%; background-color: red;">
        <!-- ko foreach: historyItems -->
        <p data-bind="text: $data"></p>
        <!-- /ko -->
    </div>
</div>

<script type="text/magento-x-init">
    {
        "[data-block="visits-history"]" : {
            "Magento_Ui/js/core/app" : <?php echo $block->getJsLayout(); ?>
        }
    }
</script>