<div data-block="visits-history">
    <div data-bind="scope: 'visits_history'" style="width: 100%; background-color: red;">
        <!-- ko if historyItems.length -->
        <ol>
            <!-- ko foreach: historyItems -->
            <li><a data-bind="text: $data.title, attr: {href: $data.url, title: $data.title}"></a></li>
            <!-- /ko -->
        </ol>
        <!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-block='visits-history']" : {
            "Magento_Ui/js/core/app" : <?php echo $block->getJsLayout(); ?>
        }
    }
</script>